Ls.ms = {
	"tt": "Bahasa Melayu",

	"cols": {
		"c": "butang tindakan",
		"dur": "durasi",
		"q": "kualiti / kadar bit",
		"Ac": "kodek audio",
		"Vc": "kodek video",
		"Fmt": "format / kontena",
		"Ahash": "jumlah semak audio",
		"Vhash": "jumlah semak video",
		"Res": "resolusi",
		"T": "jenis fail",
		"aq": "kualiti audio / kadar bit",
		"vq": "kualiti video / kadar bit",
		"pixfmt": "subpensampelan / struktur piksel",
		"resw": "resolusi mengufuk",
		"resh": "resolusi menegak",
		"chs": "saluran audio",
		"hz": "kadar sampel",
	},

	"hks": [
		[
			"misc",
			["ESC", "tutup pelbagai perkara"],

			"file-manager",
			["G", "tukar paparan senarai / grid"],
			["T", "tukar lakaran kenit / ikon"],
			["⇧ A/D", "saiz lakaran kenit"],
			["ctrl-K", "padam yang dipilih"],
			["ctrl-X", "potong pilihan ke papan klip"],
			["ctrl-C", "salin pilihan ke papan klip"],
			["ctrl-V", "tampal (pindah/salin) di sini"],
			["Y", "muat turun yang dipilih"],
			["F2", "tukar nama yang dipilih"],

			"file-list-sel",
			["space", "tukar pilihan fail"],
			["↑/↓", "gerakkan kursor pilihan"],
			["ctrl ↑/↓", "gerakkan kursor dan tetingkap tontonan"],
			["⇧ ↑/↓", "pilih fail sebelum/seterusnya"],
			["ctrl-A", "pilih semua fail / folder"],
		], [
			"navigation",
			["B", "tukar jejak serbuk roti / anak tetingkap navigasi"],
			["I/K", "folder sebelum/seterusnya"],
			["M", "folder induk (atau sembunyikan folder semasa)"],
			["V", "tukar folder / fail teks dalam anak tetingkap navigasi"],
			["A/D", "saiz anak tetingkap navigasi"],
		], [
			"audio-player",
			["J/L", "lagu sebelum/seterusnya"],
			["U/O", "langkau 10 saat ke belakang/hadapan"],
			["0..9", "lompat ke 0%..90%"],
			["P", "main/jeda (juga memulakan penstriman)"],
			["S", "pilih lagu yang sedang dimainkan"],
			["Y", "muat turun lagu"],
		], [
			"image-viewer",
			["J/L, ←/→", "gambar sebelum/seterusnya"],
			["Home/End", "gambar pertama/terakhir"],
			["F", "skrin penuh"],
			["R", "putar mengikut arah jam"],
			["⇧ R", "putar lawan arah jam"],
			["S", "pilih gambar"],
			["Y", "muat turun gambar"],
		], [
			"video-player",
			["U/O", "langkau 10 saat ke belakang/hadapan"],
			["P/K/Space", "main/jeda"],
			["C", "terus mainkan lagu/video seterusnya"],
			["V", "gelung automatik"],
			["M", "senyap"],
			["[ and ]", "tetapkan selang masa gelung"],
		], [
			"textfile-viewer",
			["I/K", "fail sebelum/seterusnya"],
			["M", "tutup fail teks"],
			["E", "edit fail teks"],
			["S", "pilih fail (untuk potong/salin/tukar nama)"],
			["Y", "muat turun fail teks"],
			["⇧ J", "kemaskan susunan json"],
		]
	],

	"m_ok": "OK",
	"m_ng": "Batal",

	"enable": "Aktifkan",
	"danger": "BAHAYA",
	"clipped": "disalin ke papan klip",

	"ht_s1": "saat",
	"ht_s2": "saat",
	"ht_m1": "minit",
	"ht_m2": "minit",
	"ht_h1": "jam",
	"ht_h2": "jam",
	"ht_d1": "hari",
	"ht_d2": "hari",
	"ht_and": " dan ",

	"goh": "panel-kawalan",
	"gop": 'previous sibling">sebelumnya',
	"gou": 'parent folder">ke atas',
	"gon": 'next folder">seterusnya',
	"logout": "Log keluar ",
	"login": "Log masuk",
	"access": " akses",
	"ot_close": "tutup submenu",
	"ot_search": "`cari fail mengikut atribut, laluan / nama, tag muzik, atau sebarang kombinasi atribut tersebut$N$N`foo bar` = mesti mengandungi kedua-dua «foo» dan «bar»,$N`foo -bar` = mesti mengandungi «foo» tetapi tanpa «bar»,$N`^yana .opus$` = bermula dengan «yana» dan merupakan fail «opus»$N`&quot;try unite&quot;` = mengandungi frasa tepat «try unite»$N$Nformat tarikh adalah jenis iso-8601, seperti$N`2009-12-31` atau `2020-09-12 23:30:00`",
	"ot_unpost": "unpost: padam muat naik terbaharu anda, atau batalkan proses muat naik yang belum selesai",
	"ot_bup": "bup: pemuat naik asas, turut menyokong netscape 4.0",
	"ot_mkdir": "mkdir: bina direktori baharu",
	"ot_md": "new-file: bina fail teks baharu",
	"ot_msg": "msg: hantar mesej ke log pelayan",
	"ot_mp": "pilihan pemain media",
	"ot_cfg": "pilihan konfigurasi",
	"ot_u2i": 'up2k: muat naik fail (jika anda mempunyai akses menulis) atau tukar ke mod carian untuk melihat sama ada fail tersebut wujud di mana-mana bahagian pelayan$N$Nmuat naik boleh disambung semula, berulir berbilang (multithreaded), dan pengepala masa fail akan dikekalkan, tetapi proses ini menggunakan lebih banyak CPU berbanding [🎈]&nbsp;(pemuat naik asas)<br /><br />semasa muat naik berjalan, ikon ini akan bertukar menjadi penunjuk kemajuan!',
	"ot_u2w": 'up2k: muat naik fail dengan sokongan sambung semula (tutup pelayar anda dan lepaskan fail yang sama kemudian)$N$Nberulir berbilang, dan pengepala masa fail akan dikekalkan, tetapi proses ini menggunakan lebih banyak CPU berbanding [🎈]&nbsp;(pemuat naik asas)<br /><br />semasa muat naik berjalan, ikon ini akan bertukar menjadi penunjuk kemajuan!',
	"ot_noie": 'Sila gunakan Chrome / Firefox / Edge',

	"ab_mkdir": "bina direktori",
	"ab_mkdoc": "fail teks baharu",
	"ab_msg": "hantar msg ke log srv",

	"ay_path": "langkau ke folder",
	"ay_files": "langkau ke fail",

	"wt_ren": "tukar nama item yang dipilih$NPintasan: F2",
	"wt_del": "padam item yang dipilih$NPintasan: ctrl-K",
	"wt_cut": "potong item yang dipilih &lt;small&gt;(kemudian tampal di tempat lain)&lt;/small&gt;$NPintasan: ctrl-X",
	"wt_cpy": "salin item yang dipilih ke papan klip$N(untuk ditampal di tempat lain)$NPintasan: ctrl-C",
	"wt_pst": "tampal pilihan yang telah dipotong / disalin sebelumnya$NPintasan: ctrl-V",
	"wt_selall": "pilih semua fail$NPintasan: ctrl-A (apabila fail difokuskan)",
	"wt_selinv": "songsangkan pilihan",
	"wt_zip1": "muat turun folder ini sebagai arkib zip",
	"wt_selzip": "muat turun pilihan sebagai arkib zip",
	"wt_seldl": "muat turun pilihan sebagai fail berasingan$NPintasan: Y",
	"wt_npirc": "salin maklumat trek berformat IRC",
	"wt_nptxt": "salin maklumat trek dalam bentuk teks biasa",
	"wt_m3ua": "tambah ke senarai main m3u (klik <code>📻salin</code> kemudian)",
	"wt_m3uc": "salin senarai main m3u ke papan klip",
	"wt_grid": "tukar pandangan grid / senarai$NPintasan: G",
	"wt_prev": "trek sebelum ini$NPintasan: J",
	"wt_play": "main / jeda$NPintasan: P",
	"wt_next": "trek seterusnya$NPintasan: L",

	"ul_par": "muat naik selari:",
	"ut_rand": "rawakkan nama fail",
	"ut_u2ts": "salin cap masa terakhir diubah suai$Ndaripada sistem fail anda ke pelayan\">📅",
	"ut_ow": "tulis ganti fail sedia ada di pelayan?$N🛡️: jangan sekali-kali (nama fail baharu akan dijana sebaliknya)$N🕒: tulis ganti jika fail pelayan lebih lama daripada fail anda$N♻️: sentiasa tulis ganti jika kandungan fail berbeza$N⏭️: langkau tanpa syarat bagi semua fail sedia ada",
	"ut_mt": "teruskan pengiraan cincangan (hashing) fail lain semasa memuat naik$N$Nboleh dinyahaktifkan jika CPU atau HDD anda menjadi kekangan buntu",
	"ut_ask": 'minta pengesahan sebelum muat naik bermula">💭',
	"ut_pot": "tingkatkan kelajuan muat naik pada peranti perlahan$Ndengan mengurangkan kerumitan UI",
	"ut_srch": "jangan muat naik, sebaliknya semak sama ada fail sudah wujud$N di pelayan (akan mengimbas semua folder yang boleh anda baca)",
	"ut_par": "jeda muat naik dengan menetapkannya kepada 0$N$Ntingkatkan jika sambungan anda perlahan / kualiti kependaman tinggi$N$Nkekalkan nilai 1 pada rangkaian LAN atau jika HDD pelayan adalah kekangan buntu",
	"ul_btn": "lepaskan fail / folder<br>di sini (atau klik saya)",
	"ul_btnu": "M U A T &nbsp; N A I K",
	"ul_btns": "C A R I A N",

	"ul_hash": "cincang",
	"ul_send": "hantar",
	"ul_done": "selesai",
	"ul_idle1": "tiada muat naik dalam baris gilir lagi",
	"ut_etah": "purata kelajuan &lt;em&gt;pencincangan&lt;/em&gt;, dan anggaran masa sehingga selesai",
	"ut_etau": "purata kelajuan &lt;em&gt;muat naik&lt;/em&gt; dan anggaran masa sehingga selesai",
	"ut_etat": "purata kelajuan &lt;em&gt;keseluruhan&lt;/em&gt; dan anggaran masa sehingga selesai",

	"uct_ok": "selesai dengan jaya",
	"uct_ng": "gagal / ditolak / tidak ditemui",
	"uct_done": "gabungan status ok dan gagal",
	"uct_bz": "sedang mencincang atau memuat naik",
	"uct_q": "melahu, tertangguh",

	"utl_name": "nama fail",
	"utl_ulist": "senarai",
	"utl_ucopy": "salin",
	"utl_links": "pautan",
	"utl_stat": "status",
	"utl_prog": "kemajuan",

	// kekalkan pendek:
	"utl_404": "404",
	"utl_err": "RALAT",
	"utl_oserr": "Ralat-OS",
	"utl_found": "ditemui",
	"utl_defer": "tangguh",
	"utl_yolo": "YOLO",

	"ul_flagblk": "fail telah ditambahkan ke baris gilir</b><br>walau bagaimanapun terdapat proses up2k yang sibuk pada tab pelayar lain,<br>jadi menunggu proses itu selesai terlebih dahulu",
	"ul_btnlk": "konfigurasi pelayan telah mengunci suis ini pada keadaan semasa",

	"udt_up": "Muat Naik",
	"udt_srch": "Cari",
	"udt_drop": "lepaskan di sini",

	"u_nav_m": '<h6>baiklah, apa yang anda ada?</h6><code>Enter</code> = Fail (satu atau lebih)\n<code>ESC</code> = Satu folder (termasuk subfolder)',
	"u_nav_b": '<a href="#" id="modal-ok">Fail</a><a href="#" id="modal-ng">Satu folder</a>',

	"cl_opts": "suis",
	"cl_hfsz": "saiz fail",
	"cl_themes": "tema",
	"cl_langs": "bahasa",
	"cl_ziptype": "muat turun folder",
	"cl_uopts": "suis up2k",
	"cl_favico": "favicon",
	"cl_bigdir": "direktori besar",
	"cl_hsort": "#isih",
	"cl_keytype": "notasi kekunci",
	"cl_hiddenc": "lajur tersembunyi",
	"cl_hidec": "sembunyi",
	"cl_reset": "set semula",
	"cl_hpick": "ketik pada pengepala lajur untuk menyembunyikannya dalam jadual di bawah",
	"cl_hcancel": "penyembunyian lajur dibatalkan",
	"cl_rcm": "menu klik kanan",
	"cl_gauto": "autogrid",

	"ct_grid": '田 grid',
	"ct_ttips": '◔ ◡ ◔">ℹ️ tip alat',
	"ct_thumb": 'dalam paparan grid, tukar ikon atau lakaran kenit$NPintasan: T">🖼️ lakaran',
	"ct_csel": 'gunakan CTRL dan SHIFT untuk pilihan fail dalam paparan grid">pilih',
	"ct_dsel": 'gunakan pilihan seret dalam paparan grid">pilih_seret',
	"ct_dl": 'paksa muat turun (jangan papar dalam talian) apabila fail diklik">muat_turun',
	"ct_ihop": 'apabila pemapar imej ditutup, skrol ke bawah ke fail terakhir dilihat">skrol_bawah⮯',
	"ct_dots": 'papar fail tersembunyi (jika pelayan membenarkan)">fail_titik',
	"ct_qdel": 'apabila memadam fail, hanya minta pengesahan sekali sahaja">padam_pantas',
	"ct_dir1st": 'isih folder sebelum fail">📁 dahulu',
	"ct_nsort": 'isihan semula jadi (untuk nama fail dengan digit awalan)">isih_asli',
	"ct_utc": 'papar semua masa tarikh dalam format UTC">UTC',
	"ct_readme": 'papar README.md dalam senarai folder">📜 readme',
	"ct_idxh": 'papar index.html berbanding senarai folder">htm',
	"ct_sbars": 'papar bar skrol">⟊',

	"cut_umod": "jika fail sudah wujud pada pelayan, kemas kini cap masa terakhir diubah suai pelayan untuk sepadan dengan fail tempatan anda (memerlukan kebenaran tulis+padam)\">re📅",

	"cut_turbo": "butang yolo, anda berkemungkinan besar TIDAK mahu mengaktifkan ini:$N$Ngunakan ini jika anda memuat naik sejumlah besar fail dan terpaksa memulakan semula atas sebab tertentu, dan mahu meneruskan muat naik secepat mungkin$N$Nini menggantikan semakan cincangan dengan semakan mudah <em>&quot;adakah ini mempunyai saiz fail yang sama pada pelayan?&quot;</em> jadi jika kandungan fail berbeza ia TIDAK akan dimuat naik$N$Nanda harus mematikan suis ini apabila muat naik selesai, dan kemudian &quot;muat naik&quot; fail yang sama semula untuk membiarkan klien mengesahkannya\">turbo",

	"cut_datechk": "tidak memberi sebarang kesan melainkan butang turbo diaktifkan$N$Nmengurangkan risiko yolo dengan jumlah yang kecil; menyemak sama ada cap masa fail pada pelayan sepadan dengan fail anda$N$Nsepatutnya <em>secara teori</em> mengesan kebanyakan muat naik yang tidak selesai / rosak, tetapi bukan pengganti untuk melakukan langkah pengesahan dengan fungsi turbo dinyahaktifkan selepas itu\">semakan-tarikh",

	"cut_u2sz": "saiz (dalam MiB) bagi setiap ketulan muat naik; nilai besar terbang lebih baik merentasi lautan altantik. Cuba nilai rendah pada sambungan yang sangat tidak stabil",

	"cut_flag": "pastikan hanya satu tab sahaja yang memuat naik pada satu-satu masa $N -- tab lain mesti mengaktifkan ini juga $N -- hanya menjejaskan tab pada domain yang sama",

	"cut_az": "muat naik fail mengikut susunan abjad, berbanding fail terkecil dahulu$N$Nsusunan abjad boleh memudahkan pemantauan mata jika berlaku ralat pada pelayan, tetapi ia menjadikan muat naik sedikit perlahan pada sambungan gentian optik / LAN",

	"cut_nag": "Notifikasi OS apabila muat naik selesai$N(hanya jika pelayar atau tab tidak aktif)",
	"cut_sfx": "Amaran berbunyi apabila muat naik selesai$N(hanya jika pelayar atau tab tidak aktif)",

	"cut_mt": "gunakan berulir berbilang (multithreading) untuk mempercepatkan pencincangan fail$N$Nini menggunakan web-workers dan memerlukan$Nlebih banyak RAM (sehingga 512 MiB tambahan)$N$Nmenjadikan https 30% lebih pantas, http 4.5x lebih pantas\">mt",

	"cut_wasm": "gunakan wasm berbanding pencincang terbina dalam pelayar; meningkatkan kelajuan pada pelayar berasaskan chrome tetapi meningkatkan bebanan CPU, dan banyak versi lama chrome mempunyai pepijat yang membuatkan pelayar menggunakan semua RAM dan ranap jika ini diaktifkan\">wasm",

	"cft_text": "teks favicon (kosongkan dan segar semula untuk menyahaktifkan)",
	"cft_fg": "warna latar hadapan",
	"cft_bg": "warna latar belakang",

	"cdt_lim": "bilangan maksimum fail untuk dipaparkan dalam folder",
	"cdt_ask": "apabila skrol ke bawah,$Nberbanding memuatkan lebih banyak fail,$Ntanya tindakan seterusnya",
	"cdt_hsort": "`berapa banyak peraturan isihan (`,sorthref`) untuk dimasukkan ke dalam URL media. Menetapkan nilai ini kepada 0 juga akan mengabaikan peraturan isihan yang terkandung dalam pautan media apabila mengkliknya",
	"cdt_ren": "aktifkan menu klik kanan tersuai, anda masih boleh mengakses menu biasa dengan menekan kekunci shift dan klik kanan\">aktifkan",
	"cdt_rdb": "papar menu klik kanan biasa apabila menu tersuai sudah sedia terbuka dan melakukan klik kanan sekali lagi\">dua_kali",

	"tt_entree": "papar anak tetingkap navigasi (sidebar pokok direktori)$NPintasan: B",
	"tt_detree": "papar jejak serbuk roti$NPintasan: B",
	"tt_visdir": "skrol ke folder yang dipilih",
	"tt_ftree": "tukar pokok folder / fail teks$NPintasan: V",
	"tt_pdock": "papar folder induk dalam panel yang doking di bahagian atas",
	"tt_dynt": "tumbuh secara dinamik apabila pepohon berkembang",
	"tt_wrap": "balut baris teks",
	"tt_hover": "paparkan baris yang melimpah apabila tetikus dilayangkan$N( menghentikan skrol melainkan penunjuk tetikus $N&nbsp; berada di longkang kiri )",
	"tt_gauto": "papar sebagai grid atau senarai bergantung kepada kandungan folder",
	"tt_gathr": "gunakan paparan grid jika peratusan fail ini terdiri daripada gambar/video",

	"ml_pmode": "di penghujung folder...",
	"ml_btns": "perintah",
	"ml_tcode": "transkod",
	"ml_tcode2": "transkod ke",
	"ml_tint": "warna corak",
	"ml_eq": "penyama audio (equalizer)",
	"ml_drc": "pemampat julat dinamik",
	"ml_ss": "langkau senyap",

	"mt_loop": "gelung/ulang satu lagu\">🔁",
	"mt_one": "berhenti selepas satu lagu\">1️⃣",
	"mt_shuf": "rawakkan lagu dalam setiap folder\">🔀",
	"mt_aplay": "main automatik jika terdapat ID lagu dalam pautan yang anda klik untuk mengakses pelayan$N$Nmenyahaktifkan ini juga akan menghentikan URL halaman daripada dikemas kini dengan ID lagu semasa memainkan muzik, untuk mengelakkan main automatik jika tetapan ini hilang tetapi URL kekal\">a▶",
	"mt_preload": "mula memuatkan lagu seterusnya berhampiran penghujung untuk main balik tanpa jurang (gapless)\">pramuat",
	"mt_prescan": "pergi ke folder seterusnya sebelum lagu terakhir$Ntamat, memastikan pelayar web kekal lancar$Nsupaya ia tidak menghentikan main balik\">nav",
	"mt_fullpre": "cuba pramuat keseluruhan lagu;$N✅ aktifkan pada sambungan yang <b>tidak stabil</b>,$N❌ <b>nyahaktifkan</b> pada sambungan yang perlahan kemungkinan besar\">penuh",
	"mt_fau": "pada telefon, elakkan muzik daripada berhenti jika lagu seterusnya tidak dipramuat dengan cukup pantas (boleh menyebabkan paparan tag menjadi pincang)\">☕️",
	"mt_waves": "bar penjejak gelombang bunyi:$Npapar amplitud audio dalam bar skrub\">~s",
	"mt_npclip": "papar butang untuk menyalin lagu yang sedang dimainkan ke papan klip\">/np",
	"mt_m3u_c": "papar butang untuk menyalin lagu yang$Ndipilih sebagai entri senarai main m3u8\">📻",
	"mt_octl": "integrasi OS (kekunci pintas media / OSD)\">kawalan-os",
	"mt_oseek": "benarkan penjejakan melalui integrasi OS$N$Nnota: pada sesetengah peranti (iPhone),$Nini menggantikan butang lagu seterusnya\">jejak",
	"mt_oscv": "papar seni album dalam OSD\">seni",
	"mt_follow": "pastikan trek yang sedang dimainkan diskrol ke dalam paparan\">🎯",
	"mt_compact": "kawalan padat\">⟎",
	"mt_uncache": "kosongkan cache &nbsp;(cuba ini jika pelayar anda menyimpan salinan lagu yang rosak dalam cache menyebabkan ia enggan dimainkan)\">kosongkan_cache",
	"mt_mloop": "gelung folder yang terbuka\">🔁 gelung",
	"mt_mnext": "muat folder seterusnya dan teruskan\">📂 seterusnya",
	"mt_mstop": "hentikan main balik\">⏸ henti",
	"mt_cflac": "tukar flac / wav kepada {0}\">flac",
	"mt_caac": "tukar aac / m4a kepada {0}\">aac",
	"mt_coth": "tukar semua yang lain (bukan mp3) kepada {0}\">lain-lain",
	"mt_c2opus": "pilihan terbaik untuk desktop, komputer riba, android\">opus",
	"mt_c2owa": "opus-weba, untuk iOS 17.5 dan lebih baharu\">owa",
	"mt_c2caf": "opus-caf, untuk iOS 11 hingga 17\">caf",
	"mt_c2mp3": "gunakan ini pada peranti yang sangat lama\">mp3",
	"mt_c2flac": "kualiti bunyi terbaik, tetapi saiz muat turun sangat besar\">flac",
	"mt_c2wav": "main balik tanpa mampatan (lebih besar)\">wav",
	"mt_c2ok": "terbaik, pilihan yang bagus",
	"mt_c2nd": "itu bukan format output yang disyorkan untuk peranti anda, tetapi tidak mengapa",
	"mt_c2ng": "peranti anda nampaknya tidak menyokong format output ini, tetapi mari kita cuba juga",
	"mt_xowa": "terdapat pepijat dalam iOS yang menghalang main balik latar belakang menggunakan format ini; sila gunakan caf atau mp3 sebagai ganti",
	"mt_tint": "tahap latar belakang (0-100) pada bar penjejak untuk mengurangkan gangguan penimbunan (buffering)",

	"mt_eq": "`membolehkan kawalan penyama (equalizer) dan ganjaran (gain);$N$Nboost `0` = volum standard 100% (tanpa pengubahsuaian)$N$Nwidth `1 &nbsp;` = stereo standard (tanpa pengubahsuaian)$Nwidth `0.5` = 50% suapan silang kiri-kanan$Nwidth `0 &nbsp;` = mono$N$Nboost `-0.8` &amp; width `10` = penyingkiran vokal :^)$N$Nmembolehkan fungsi penyama menjadikan album tanpa jurang sepenuhnya lancar, jadi biarkan ia aktif dengan semua nilai pada sifar (kecuali lebar = 1) jika anda mementingkan perkara itu",
	"mt_drc": "membolehkan pemampat julat dinamik (perata volum / pembatas tegar); juga akan mengaktifkan EQ untuk mengimbangi kekacauan bunyi, jadi tetapkan semua medan EQ kecuali 'width' kepada 0 jika anda tidak mahukannya$N$Nmerendahkan volum audio di atas AMBANG dB; bagi setiap RATIO dB melepasi AMBANG terdapat 1 dB output, jadi nilai lalai 'tresh' -24 dan 'ratio' 12 bermakna ia tidak akan menjadi lebih kuat daripada -22 dB dan adalah selamat untuk meningkatkan rangsangan equalizer kepada 0.8, atau 1.8 dengan ATK 0 dan RLS yang besar seperti 90 (hanya berfungsi di firefox; RLS adalah maksimum 1 di pelayar lain)$N$N(lihat wikipedia, mereka menerangkan perkara ini dengan jauh lebih baik)",
	"mt_ss": "`membolehkan fungsi langkau senyap; menggandakan kelajuan main balik dengan nilai `ffwd` berhampiran permulaan/penghujung lagu apabila volum berada di bawah nilai `vol` dan kedudukan main balik berada dalam julat `start` % pertama atau `end` % terakhir trek",
	"mt_ssvt": "ambang volum (0-255)\">vol",
	"mt_ssts": "ambang aktif (% daripada trek, mula)\">start",
	"mt_sste": "ambang aktif (% daripada trek, tamat)\">end",
	"mt_sssm": "gandaan kelajuan main balik (julat: 0.15 hingga 8)\">ffwd",

	"mb_play": "main",
	"mm_hashplay": "mainkan fail audio ini?",
	"mm_m3u": "tekan <code>Enter/OK</code> untuk Main\ntekan <code>ESC/Batal</code> untuk Edit",
	"mp_breq": "memerlukan firefox 82+ atau chrome 73+ atau iOS 15+",
	"mm_bload": "sedang memuatkan...",
	"mm_bconv": "menukar kepada {0}, sila tunggu...",
	"mm_opusen": "pelayar anda tidak boleh memainkan fail aac / m4a;\ntranskod kepada opus kini diaktifkan",
	"mm_playerr": "main balik gagal: ",
	"mm_eabrt": "Cubaan main balik telah dibatalkan",
	"mm_enet": "Sambungan internet anda tidak stabil",
	"mm_edec": "Fail ini kononnya rosak??",
	"mm_esupp": "Pelayar anda tidak memahami format audio ini",
	"mm_eunk": "Ralat Tidak Diketahui",
	"mm_e404": "Tidak dapat memainkan audio; ralat 404: Fail tidak ditemui.",
	"mm_e403": "Tidak dapat memainkan audio; ralat 403: Akses ditolak.\n\nCuba tekan F5 untuk memuatkan semula, mungkin sesi log masuk anda telah tamat",
	"mm_e415": "Tidak dapat memainkan audio; ralat 415: Transkod fail gagal; semak log pelayan.",
	"mm_e500": "Tidak dapat memainkan audio; ralat 500: Semak log pelayan.",
	"mm_e5xx": "Tidak dapat memainkan audio; ralat pelayan ",
	"mm_nof": "tidak menemui sebarang fail audio berdekatan",
	"mm_prescan": "Mencari muzik untuk dimainkan seterusnya...",
	"mm_scank": "Menemui lagu seterusnya:",
	"mm_uncache": "cache dibatalkan; semua lagu akan dimuat turun semula pada main balik seterusnya",
	"mm_hnf": "lagu itu tidak lagi wujud",

	"im_hnf": "imej itu tidak lagi wujud",

	"f_empty": 'folder ini kosong',
	"f_chide": 'ini akan menyembunyikan lajur «{0}»\n\nanda boleh memaparkan semula lajur dalam tab tetapan',
	"f_bigtxt": "fail ini bersaiz {0} MiB -- benar-benar mahu lihat sebagai teks?",
	"f_bigtxt2": "lihat bahagian penghujung fail sahaja sebagai ganti? ini juga akan membolehkan fungsi ekor/ikut (tailing), memaparkan baris teks yang baru ditambah secara masa nyata",
	"f_anota": "hanya {0} daripada {1} item dipilih;\nuntuk memilih keseluruhan folder, skrol ke bawah terlebih dahulu",

	"fbd_more": '<div id="blazy">memaparkan <code>{0}</code> daripada <code>{1}</code> fail; <a href="#" id="bd_more">papar {2}</a> atau <a href="#" id="bd_all">papar semua</a></div>',
	"fbd_all": '<div id="blazy">memaparkan <code>{0}</code> daripada <code>{1}</code> fail; <a href="#" id="bd_all">papar semua</a></div>',

	"f_dls": 'pautan fail dalam folder semasa telah\ndiubah menjadi pautan muat turun',
	"f_dl_nd": 'melangkau folder (gunakan muat turun zip/tar sebaliknya):\n',

	"f_partial": "Untuk memuat turun fail yang sedang dimuat naik secara selamat, sila klik fail yang mempunyai nama yang sama, tetapi tanpa sambungan fail <code>.PARTIAL</code>. Sila tekan BATAL atau Escape untuk melakukan ini.\n\nMenekan OK / Enter akan mengabaikan amaran ini dan meneruskan muat turun fail calar <code>.PARTIAL</code>, yang hampir pasti akan memberikan anda data yang rosak.",

	"ft_paste": "tampal {0} item$NPintasan: ctrl-V",
	"fr_eperm": 'tidak boleh menukar nama:\nanda tidak mempunyai kebenaran “pindah” dalam folder ini',
	"fd_eperm": 'tidak boleh memadam:\nanda tidak mempunyai kebenaran “padam” dalam folder ini',
	"fc_eperm": 'tidak boleh memotong:\nanda tidak mempunyai kebenaran “pindah” dalam folder ini',
	"fp_eperm": 'tidak boleh menampal:\nanda tidak mempunyai kebenaran “tulis” dalam folder ini',
	"fr_emore": "pilih sekurang-kurangnya satu item untuk ditukar nama",
	"fd_emore": "pilih sekurang-kurangnya satu item untuk dipadam",
	"fc_emore": "pilih sekurang-kurangnya satu item untuk dipotong",
	"fcp_emore": "pilih sekurang-kurangnya satu item untuk disalin ke papan klip",

	"fs_sc": "kongsi folder tempat anda berada",
	"fs_ss": "kongsi fail yang dipilih",
	"fs_just1d": "anda tidak boleh memilih lebih daripada satu folder,\natau mencampurkan fail dan folder dalam satu pilihan",
	"fs_abrt": "❌ batal",
	"fs_rand": "🎲 nama_rawak",
	"fs_go": "✅ bina perkongsian",
	"fs_name": "nama",
	"fs_src": "sumber",
	"fs_pwd": "kata_laluan",
	"fs_exp": "luput",
	"fs_tmin": "minit",
	"fs_thrs": "jam",
	"fs_tdays": "hari",
	"fs_never": "abadi",
	"fs_pname": "nama pautan pilihan; akan dirawakkan jika dibiarkan kosong",
	"fs_tsrc": "fail atau folder untuk dikongsi",
	"fs_ppwd": "kata laluan pilihan",
	"fs_w8": "membina perkongsian...",
	"fs_ok": "tekan <code>Enter/OK</code> untuk Papan Klip\ntekan <code>ESC/Batal</code> untuk Tutup",

	"frt_dec": "boleh menyelesaikan beberapa kes nama fail yang rosak\">dekod-url",
	"frt_rst": "set semula nama fail yang diubah suai kembali ke nama asal\">↺ set semula",
	"frt_abrt": "batal dan tutup tetingkap ini\">❌ batal",
	"frb_apply": "APLIKASIKAN PERTUKARAN NAMA",
	"fr_adv": "pertukaran nama kelompok / metadata / corak\">lanjutan",
	"fr_case": "regex peka huruf\">huruf",
	"fr_win": "nama selamat windows; gantikan <code>&lt;&gt;:&quot;\\|?*</code> dengan aksara lebar penuh jepun\">win",
	"fr_slash": "gantikan <code>/</code> dengan aksara yang tidak menyebabkan folder baharu dibina\">tiada /",
	"fr_re": "`corak carian regex untuk diaplikasikan pada nama fail asal; kumpulan penangkap boleh dirujuk dalam medan format di bawah seperti `(1)` dan `(2)` dan seterusnya",
	"fr_fmt": "`diispirasikan oleh foobar2000:$N`(title)` digantikan dengan tajuk lagu,$N`[(artist) - ](title)` melangkau bahagian [ini] jika nama artis kosong$N`$lpad((tn),2,0)` menambah sifar padat pada nombor trek menjadi 2 digit",
	"fr_pdel": "padam",
	"fr_pnew": "simpan sebagai",
	"fr_pname": "sediakan nama untuk praset baharu anda",
	"fr_aborted": "dibatalkan",
	"fr_lold": "nama lama",
	"fr_lnew": "nama baharu",
	"fr_tags": "tag untuk fail yang dipilih (baca sahaja, hanya untuk rujukan):",
	"fr_busy": "menukar nama {0} item...\n\n{1}",
	"fr_efail": "pertukaran nama gagal:\n",
	"fr_nchg": "{0} daripada nama baharu telah diubah disebabkan oleh tetapan <code>win</code> dan/atau <code>tiada /</code>\n\nOK untuk meneruskan dengan nama baharu yang telah diubah ini?",

	"fd_ok": "pemadaman OK",
	"fd_err": "pemadaman gagal:\n",
	"fd_none": "tiada apa yang dipadamkan; mungkin disekat oleh konfigurasi pelayan (xbd)?",
	"fd_busy": "memadam {0} item...\n\n{1}",
	"fd_warn1": "PADAM {0} item ini?",
	"fd_warn2": "<b>Peluang terakhir!</b> Tiada cara untuk buat asal. Padam?",

	"fc_ok": "memotong {0} item",
	"fc_warn": 'memotong {0} item\n\ntetapi: hanya tab pelayar JALUR INI yang boleh menampalnya\n(kerana saiz pilihan adalah sangat besar)',

	"fcc_ok": "menyalin {0} item ke papan klip",
	"fcc_warn": 'menyalin {0} item ke papan klip\n\ntetapi: hanya tab pelayar JALUR INI yang boleh menampalnya\n(kerana saiz pilihan adalah sangat besar)',

	"fp_apply": "gunakan nama ini",
	"fp_skip": "langkau konflik",
	"fp_ecut": "potong atau salin beberapa fail / folder terlebih dahulu untuk menampal / memindah\n\nnota: anda boleh memotong / menampal merentasi tab pelayar yang berbeza",
	"fp_ename": "{0} item tidak boleh dipindahkan ke sini kerana nama tersebut telah digunakan. Sediakan nama baharu di bawah untuk meneruskan, atau kosongkan nama (\"langkau konflik\") untuk melangkaunya:",
	"fcp_ename": "{0} item tidak boleh disalin ke sini kerana nama tersebut telah digunakan. Sediakan nama baharu di bawah untuk meneruskan, atau kosongkan nama (\"langkau konflik\") untuk melangkaunya:",
	"fp_emore": "masih terdapat beberapa perlanggaran nama fail yang perlu diperbaiki",
	"fp_ok": "pindahan OK",
	"fcp_ok": "salinan OK",
	"fp_busy": "memindahkan {0} item...\n\n{1}",
	"fcp_busy": "menyalin {0} item...\n\n{1}",
	"fp_abrt": "membatalkan...",
	"fp_err": "pindahan gagal:\n",
	"fcp_err": "salinan gagal:\n",
	"fp_confirm": "pindahkan {0} item ini ke sini?",
	"fcp_confirm": "salin {0} item ini ke sini?",
	"fp_etab": 'gagal membaca papan klip daripada tab pelayar lain',
	"fp_name": "memuat naik fail daripada peranti anda. Berikan ia nama:",
	"fp_both_m": '<h6>pilih apa yang hendak ditampal</h6><code>Enter</code> = Pindah {0} fail daripada «{1}»\n<code>ESC</code> = Muat naik {2} fail daripada peranti anda',
	"fcp_both_m": '<h6>pilih apa yang hendak ditampal</h6><code>Enter</code> = Salin {0} fail daripada «{1}»\n<code>ESC</code> = Muat naik {2} fail daripada peranti anda',
	"fp_both_b": '<a href="#" id="modal-ok">Pindah</a><a href="#" id="modal-ng">Muat naik</a>',
	"fcp_both_b": '<a href="#" id="modal-ok">Salin</a><a href="#" id="modal-ng">Muat naik</a>',

	"mk_noname": "taip nama ke dalam medan teks di sebelah kiri sebelum anda melakukan perkara itu :p",
	"nmd_i1": "juga masukkan sambungan fail yang anda mahukan, contohnya <code>.md</code>",
	"nmd_i2": "anda hanya boleh membina fail <code>.{0}</code> kerana anda tidak mempunyai kebenaran memadam",

	"tv_load": "Memuatkan dokumen teks:\n\n{0}\n\n{1}% ({2} daripada {3} MiB dimuatkan)",
	"tv_xe1": "tidak dapat memuatkan fail teks:\n\nralat ",
	"tv_xe2": "404, fail tidak ditemui",
	"tv_lst": "senarai fail teks dalam",
	"tvt_close": "kembali ke paparan folder$NPintasan: M (atau Esc)\">❌ tutup",
	"tvt_dl": "muat turun fail ini$NPintasan: Y\">💾 muat turun",
	"tvt_prev": "papar dokumen sebelum ini$NPintasan: i\">⬆ sblm",
	"tvt_next": "papar dokumen seterusnya$NPintasan: K\">⬇ sttrs",
	"tvt_sel": "pilih fail &nbsp; ( untuk potong / salin / padam / ... )$NPintasan: S\">pilih",
	"tvt_j": "kemaskan json$NPintasan: shift-J\">j",
	"tvt_edit": "buka fail dalam editor teks$NPintasan: E\">✏️ edit",
	"tvt_tail": "pantau fail untuk perubahan; papar baris baharu secara masa nyata\">📡 ikut",
	"tvt_wrap": "balut-kata\">↵",
	"tvt_atail": "kunci skrol ke bahagian bawah halaman\">⚓",
	"tvt_ctail": "dekod warna terminal (kod pelarian ansi)\">🌈",
	"tvt_ntail": "had skrol belakang (berapa banyak bait teks untuk kekal dimuatkan)",

	"m3u_add1": "lagu ditambahkan ke senarai main m3u",
	"m3u_addn": "{0} lagu ditambahkan ke senarai main m3u",
	"m3u_clip": "senarai main m3u kini disalin ke papan klip\n\nanda harus membina fail teks baharu bernama sesuatu.m3u dan menampal senarai main ke dalam dokumen tersebut; ini akan menjadikannya boleh dimainkan",

	"gt_vau": "jangan papar video, hanya mainkan audio sahaja\">🎧",
	"gt_msel": "aktifkan pilihan fail; ctrl-klik fail untuk membatalkan tetapan$N$Napabila aktif: klik dua kali fail / folder untuk membukanya$NPintasan: S\">pilihan_berbanyak",
	"gt_crop": "pangkas tengah lakaran kenit\">pangkas",
	"gt_3x": "lakaran kenit resolusi tinggi\">3x",
	"gt_zoom": "zum",
	"gt_chop": "potong",
	"gt_sort": "isih mengikut",
	"gt_name": "nama",
	"gt_sz": "saiz",
	"gt_ts": "tarikh",
	"gt_ext": "jenis",
	"gt_c1": "singkatkan nama fail dengan lebih banyak (papar kurang)",
	"gt_c2": "singkatkan nama fail dengan lebih sedikit (papar lebih)",

	"sm_w8": "mencari...",
	"sm_prev": "hasil carian di bawah adalah daripada pertanyaan sebelumnya:\n  ",
	"sl_close": "tutup hasil carian",
	"sl_hits": "memaparkan {0} padanan",
	"sl_moar": "muat banyak lagi",

	"s_sz": "saiz",
	"s_dt": "tarikh",
	"s_rd": "laluan",
	"s_fn": "nama",
	"s_ta": "tag",
	"s_ua": "dimuat_naik@",
	"s_ad": "lanjutan",
	"s_s1": "MiB minimum",
	"s_s2": "MiB maksimum",
	"s_d1": "min. iso8601",
	"s_d2": "max. iso8601",
	"s_u1": "dimuat naik selepas",
	"s_u2": "dan/atau sebelum",
	"s_r1": "laluan mengandungi &nbsp; (dipisahkan dengan jarak)",
	"s_f1": "nama mengandungi &nbsp; (nafi dengan -nope)",
	"s_t1": "tag mengandungi &nbsp; (^=mula, tamat=$)",
	"s_a1": "sifat metadata khusus",

	"md_eshow": "tidak dapat merendah ",
	"md_off": "[📜<em>readme</em>] dinyahaktifkan dalam [⚙️] -- dokumen disembunyikan",

	"badreply": "Gagal menghuraikan balasan daripada pelayan",

	"xhr403": "403: Akses ditolak\n\ncuba tekan F5, mungkin sesi log masuk anda telah tamat",
	"xhr0": "tidak diketahui (kemungkinan terputus sambungan ke pelayan, atau pelayan di luar talian)",
	"cf_ok": "kesulitan amat dikesali -- Perlindungan DD" + wah + "oS diaktifkan\n\noperasi sepatutnya bersambung semula dalam masa kira-kira 30 saat\n\njika tiada apa yang berlaku, tekan F5 untuk memuatkan semula halaman",
	"tl_xe1": "tidak dapat menyenaraikan subfolder:\n\nralat ",
	"tl_xe2": "404: Folder tidak ditemui",
	"fl_xe1": "tidak dapat menyenaraikan fail dalam folder:\n\nralat ",
	"fl_xe2": "404: Folder tidak ditemui",
	"fd_xe1": "tidak dapat membina subfolder:\n\nralat ",
	"fd_xe2": "404: Folder induk tidak ditemui",
	"fsm_xe1": "tidak dapat menghantar mesej:\n\nralat ",
	"fsm_xe2": "404: Folder induk tidak ditemui",
	"fu_xe1": "gagal memuatkan senarai unpost daripada pelayan:\n\nralat ",
	"fu_xe2": "404: Fail tidak ditemui??",

	"fz_tar": "fail gnu-tar tanpa mampatan (linux / mac)",
	"fz_pax": "tar format pax tanpa mampatan (lebih perlahan)",
	"fz_targz": "gnu-tar dengan mampatan gzip tahap 3$N$Nini biasanya sangat perlahan, jadi gunakan tar tanpa mampatan sebagai ganti",
	"fz_tarxz": "gnu-tar dengan mampatan xz tahap 1$N$Nini biasanya sangat perlahan, jadi gunakan tar tanpa mampatan sebagai ganti",
	"fz_zip8": "zip dengan nama fail utf8 (mungkin pincang pada windows 7 dan lebih lama)",
	"fz_zipd": "zip dengan nama fail cp437 tradisional, untuk perisian yang sangat lama",
	"fz_zipc": "cp437 dengan crc32 dikira awal, untuk MS-DOS PKZIP v2.04g (oktober 1993)$N(mengambil masa lebih lama untuk diproses sebelum muat turun bermula)",

	"un_m1": "anda boleh memadamkan muat naik terbaharu anda (atau batalkan yang belum selesai) di bawah",
	"un_upd": "segar semula",
	"un_m4": "atau kongsi fail yang kelihatan di bawah:",
	"un_ulist": "papar",
	"un_ucopy": "salin",
	"un_flt": "penapis pilihan:&nbsp; URL mesti mengandungi",
	"un_fclr": "kosongkan penapis",
	"un_derr": 'padam-unpost gagal:\n',
	"un_f5": 'sesuatu telah rosak, sila cuba segar semula atau tekan F5',
	"un_uf5": "maaf tetapi anda perlu menyegarkan semula halaman (contohnya dengan menekan F5 atau CTRL-R) sebelum muat naik ini boleh dibatalkan",
	"un_nou": '<b>amaran:</b> pelayan terlalu sibuk untuk memaparkan muat naik yang belum selesai; klik pautan "segar semula" dalam seketika',
	"un_noc": '<b>amaran:</b> unpost bagi fail yang dimuat naik sepenuhnya tidak diaktifkan/dibenarkan dalam konfigurasi pelayan',
	"un_max": "memaparkan 2000 fail pertama (gunakan penapis)",
	"un_avail": "{0} muat naik terbaharu boleh dipadamkan<br />{1} yang belum selesai boleh dibatalkan",
	"un_m2": "diisih mengikut masa muat naik; paling baru dahulu:",
	"un_no1": "sike! tiada muat naik yang cukup baru",
	"un_no2": "sike! tiada muat naik yang sepadan dengan penapis tersebut cukup baru",
	"un_next": "padam {0} fail seterusnya di bawah",
	"un_abrt": "batal",
	"un_del": "padam",
	"un_m3": "memuatkan muat naik terbaharu anda...",
	"un_busy": "memadam {0} fail...",
	"un_clip": "{0} pautan disalin ke papan klip",

	"u_https1": "anda patut",
	"u_https2": "tukar kepada https",
	"u_https3": "untuk prestasi lebih baik",
	"u_ancient": 'pelayar anda mengagumkan tahap purbanya -- mungkin anda patut <a href="#" onclick="goto(\'bup\')">menggunakan bup sebagai ganti</a>',
	"u_nowork": "memerlukan firefox 53+ atau chrome 57+ atau iOS 11+",
	"tail_2old": "memerlukan firefox 105+ or chrome 71+ or iOS 14.5+",
	"u_nodrop": 'pelayar anda terlalu lama untuk fungsi muat naik seret dan lepas',
	"u_notdir": "itu bukan folder!\n\npelayar anda terlalu lama,\nsila cuba seret lepas fail sebagai ganti",
	"u_uri": "untuk menyeret lepas imej daripada tetingkap pelayar lain,\nsila lepaskannya ke atas butang muat naik yang besar",
	"u_enpot": 'tukar ke <a href="#">UI kentang</a> (boleh meningkatkan kelajuan muat naik)',
	"u_depot": 'tukar ke <a href="#">UI lawa</a> (boleh mengurangkan kelajuan muat naik)',
	"u_gotpot": 'bertukar ke UI kentang untuk peningkatan kelajuan muat naik,\nsilakan tukar kembali jika anda tidak bersetuju!',
	"u_pott": "<p>fail: &nbsp; <b>{0}</b> selesai, &nbsp; <b>{1}</b> gagal, &nbsp; <b>{2}</b> sibuk, &nbsp; <b>{3}</b> dalam gilir</p>",
	"u_ever": "ini adalah pemuat naik asas; up2k memerlukan sekurang-kurangnya<br>chrome 21 // firefox 13 // edge 12 // opera 12 // safari 5.1",
	"u_su2k": 'ini adalah pemuat naik asas; <a href="#" id="u2yea">up2k</a> adalah lebih baik',
	"u_uput": 'optimumkan untuk kelajuan (langkau jumlah semak)',
	"u_ewrite": 'anda tidak mempunyai akses menulis ke folder ini',
	"u_eread": 'anda tidak mempunyai akses membaca ke folder ini',
	"u_enoi": 'carian fail tidak diaktifkan dalam konfigurasi pelayan',
	"u_enoow": "tulis ganti tidak akan berfungsi di sini; memerlukan kebenaran Padam",
	"u_badf": '{0} fail ini (daripada {1} jumlah keseluruhan) telah dilangkau, berkemungkinan disebabkan oleh kebenaran sistem fail:\n\n',
	"u_blankf": '{0} fail ini (daripada {1} jumlah keseluruhan) adalah kosong; muat naik juga?\n\n',
	"u_applef": '{0} fail ini (daripada {1} jumlah keseluruhan) berkemungkinan tidak diingini;\nTekan <code>OK/Enter</code> untuk LANGKAU fail berikut,\nTekan <code>Cancel/ESC</code> untuk TIDAK mengecualikan, dan MUAT NAIK fail tersebut juga:\n\n',
	"u_just1": '\nMungkin ia berfungsi lebih baik jika anda memilih satu fail sahaja',
	"u_ff_many": "jika anda menggunakan <b>Linux / MacOS / Android,</b> jumlah fail sebanyak ini <a href=\"https://bugzilla.mozilla.org/show_bug.cgi?id=1790500\" target=\"_blank\"><em>boleh</em> meranapkan Firefox!</a>\njika itu berlaku, sila cuba lagi (atau gunakan Chrome).",
	"u_up_life": "Muat naik ini akan dipadamkan daripada pelayan\n{0} selepas ia selesai",
	"u_asku": 'muat naik {0} fail ini ke <code>{1}</code>',
	"u_unpt": "anda boleh buat asal / memadam muat naik ini menggunakan ikon 🧯 di atas sebelah kiri",
	"u_bigtab": 'hampir memaparkan {0} fail\n\nini boleh meranapkan pelayar anda, adakah anda pasti?',
	"u_scan": 'Mengimbas fail...',
	"u_dirstuck": 'lelaran direktori tersekat semasa cuba mengakses {0} item berikut; akan dilangkau:',
	"u_etadone": 'Selesai ({0}, {1} fail)',
	"u_etaprep": '(bersedia untuk memuat naik)',
	"u_hashdone": 'pencincangan selesai',
	"u_hashing": 'cincang',
	"u_hs": 'berjabat tangan (handshaking)...',
	"u_started": "fail kini sedang dimuat naik; lihat [🚀]",
	"u_dupdefer": "pendua; akan diproses selepas semua fail lain selesai",
	"u_actx": "klik teks ini untuk mengelakkan kehilangan<br />prestasi apabila bertukar ke tetingkap/tab lain",
	"u_fixed": "OK!&nbsp; Berjaya dibetulkan 👍",
	"u_cuerr": "gagal memuat naik ketulan {0} daripada {1};\nkemungkinan tidak berbahaya, meneruskan\n\nfail: {2}",
	"u_cuerr2": "pelayan menolak muat naik (ketulan {0} daripada {1});\nakan mencuba lagi kemudian\n\nfail: {2}\n\nralat ",
	"u_ehstmp": "akan mencuba lagi; lihat bawah sebelah kanan",
	"u_ehsfin": "pelayan menolak permintaan untuk memuktamadkan muat naik; mencuba lagi...",
	"u_ehssrch": "pelayan menolak permintaan untuk melaksanakan carian; mencuba lagi...",
	"u_ehsinit": "pelayan menolak permintaan untuk memulakan muat naik; mencuba lagi...",
	"u_eneths": "ralat rangkaian semasa melaksanakan jabat tangan muat naik; mencuba lagi...",
	"u_enethd": "ralat rangkaian semasa menguji kewujudan sasaran; mencuba lagi...",
	"u_cbusy": "menunggu pelayan mempercayai kami semula selepas gangguan rangkaian...",
	"u_ehsdf": "pelayan kehabisan ruang cakera!\n\nakan terus mencuba lagi, sekiranya seseorang\nmembebaskan ruang yang mencukupi untuk meneruskan",
	"u_emtleak1": "nampaknya pelayar web anda mungkin mempunyai kebocoran memori;\nsila",
	"u_emtleak2": ' <a href="{0}">tukar kepada https (disyorkan)</a> atau ',
	"u_emtleak3": ' ',
	"u_emtleakc": 'cuba perkara berikut:\n<ul><li>tekan <code>F5</code> untuk menyegarkan halaman</li><li>kemudian nyahaktifkan butang &nbsp;<code>mt</code>&nbsp; di dalam &nbsp;<code>⚙️ tetapan</code></li><li>dan cuba muat naik itu semula</li></ul>Muat naik akan menjadi perlahan sedikit, tetapi apa boleh buat.\nMaaf atas kesulitan !\n\nPS: chrome v107 <a href="https://bugs.chromium.org/p/chromium/issues/detail?id=1354816" target="_blank">mempunyai pembaikan pepijat</a> untuk perkara ini',
	"u_emtleakf": 'cuba perkara berikut:\n<ul><li>tekan <code>F5</code> untuk menyegarkan halaman</li><li>kemudian aktifkan <code>🥔</code> (kentang) dalam UI muat naik<li>dan cuba muat naik itu semula</li></ul>\nPS: firefox <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1790500" target="_blank">diharapkan akan mempunyai pembaikan pepijat</a> pada suatu masa nanti',
	"u_s404": "tidak ditemui pada pelayan",
	"u_expl": "terangkan",
	"u_maxconn": "kebanyakan pelayar mengehadkan ini kepada 6, tetapi firefox membenarkan anda meningkatkannya dengan <code>connections-per-server</code> di dalam <code>about:config</code>",
	"u_tu": '<p class="warn">AMARAN: fungsi turbo diaktifkan, <span>&nbsp;klien mungkin tidak dapat mengesan dan menyambung semula muat naik yang tidak lengkap; lihat tip alat butang turbo</span></p>',
	"u_ts": '<p class="warn">AMARAN: fungsi turbo diaktifkan, <span>&nbsp;hasil carian boleh menjadi tidak tepat; lihat tip alat butang turbo</span></p>',
	"u_turbo_c": "fungsi turbo dinyahaktifkan dalam konfigurasi pelayan",
	"u_turbo_g": "menyahaktifkan fungsi turbo kerana anda tidak mempunyai keistimewaan penyenaraian direktori dalam volum ini",
	"u_life_cfg": 'padam automatik selepas <input id="lifem" p="60" /> minit (atau <input id="lifeh" p="3600" /> jam)',
	"u_life_est": 'muat naik akan dipadamkan pada <span id="lifew" tt="local time">---</span>',
	"u_life_max": 'folder ini menguatkuasakan jangka hayat maksimum sebanyak {0}',
	"u_unp_ok": 'unpost dibenarkan untuk {0}',
	"u_unp_ng": 'unpost TIDAK akan dibenarkan',
	"ue_ro": 'akses anda ke folder ini adalah Baca-Sahaja\n\n',
	"ue_nl": 'anda pada masa ini belum log masuk',
	"ue_la": 'anda pada masa ini log masuk sebagai "{0}"',
	"ue_sr": 'anda kini berada dalam mod carian fail\n\ntukar ke mod muat naik dengan mengklik ikon kanta pembesar 🔎 (bersebelahan butang besar CARI), dan cuba memuat naik semula\n\nmaaf',
	"ue_ta": 'cuba muat naik semula, ia sepatutnya berfungsi sekarang',
	"ue_ab": "fail ini sudah pun dimuat naik ke dalam folder lain, dan muat naik tersebut mesti diselesaikan sebelum fail boleh dimuat naik di tempat lain.\n\nAnda boleh membatalkan dan melupakan muat naik awal menggunakan ikon 🧯 di atas sebelah kiri",
	"ur_1uo": "OK: Fail berjaya dimuat naik",
	"ur_auo": "OK: Semua {0} fail berjaya dimuat naik",
	"ur_1so": "OK: Fail ditemui pada pelayan",
	"ur_aso": "OK: Semua {0} fail ditemui pada pelayan",
	"ur_1un": "Muat naik gagal, maaf",
	"ur_aun": "Semua {0} muat naik gagal, maaf",
	"ur_1sn": "Fail TIDAK ditemui pada pelayan",
	"ur_asn": "{0} fail tersebut TIDAK ditemui pada pelayan",
	"ur_um": "Selesai;\n{0} muat naik OK,\n{1} muat naik gagal, maaf",
	"ur_sm": "Selesai;\n{0} fail ditemui pada pelayan,\n{1} fail TIDAK ditemui pada pelayan",

	"rc_opn": "buka",
	"rc_ply": "main",
	"rc_pla": "main sebagai audio",
	"rc_txt": "buka dalam pemapar fail teks",
	"rc_md": "buka dalam pemapar markdown",
	"rc_dl": "muat turun",
	"rc_zip": "muat turun sebagai arkib zip",
	"rc_cpl": "salin pautan",
	"rc_del": "padam",
	"rc_cut": "potong",
	"rc_cpy": "salin",
	"rc_pst": "tampal",
	"rc_rnm": "tukar nama",
	"rc_nfo": "folder baharu",
	"rc_nfi": "fail baharu",
	"rc_sal": "pilih semua",
	"rc_sin": "songsangkan pilihan",
	"rc_shf": "kongsi folder ini",
	"rc_shs": "kongsi pilihan",

	"lang_set": "segar semula untuk membiarkan perubahan mengambil kesan?",
};